# Run "make" in project root dir.

SOURCES += \
	src/util.cpp \
	src/mem.cpp \
	src/cpu.cpp \
	src/asm_x86-64.cpp \
	src/system.cpp \
	src/mips.cpp \
  src/dma.cpp \
  src/gpu.cpp \
	src/gpu_shader.cpp \
	src/gpu_gp0.cpp \
  src/gpu_gp1.cpp \
	src/opengl-wrap.cpp \
